# School of AI - São Paulo
## Professor:   Victor Venites
## Data: 18/06/2019
- 
# ***Perceptron***

In [1]:
%%html
<marquee style='width: 100%; color: blue;'><h1><b>BASE!</b></h1></marquee>

# Base de Conhecimento
## Método Científico


*   Método de atuação das ciências exatas
*   Reprodutibilidade
*   Princípio da Falseabilidade (pressionar os dados)
*   Entenda o Método Científico e você entederá qualquer modelo a partir da base
*   Para quantas bases de dados seu modelo funciona?
*   Quais tipos de dados seu modelo atende?

## Otimização Matemática<br/>
>Aplicações: Manufatura; Transporte, Logística, Economia, etc ...<br/>
> Maximizar ou Minimizar possibílidades<br/>
> **Problema Básico:** <br/>
>  1.   Função Objetivo , * f(x)* , ou Hipótese <br/>
>  2.   Variáveis: x1, x2, x3, ... , x4, ou, "Altura", "Peso", "Idade"... <br/>
>  3.  Restrições: "Se X for menor que 2"; Regras de Negócio  <br/>
> **Pesquisa Operacional**
## Meta-Heuristicas
> N, NP, NP-Hard <br/>
> NonPlonimial
---
## Casos Pertinentes
>  - **Restrições (Constraints em Inglês):** Limitados, ou Não Limitados<br/>
>  - Variáveis Discretas ou Continuas
>  - Deterministicas, Stocasticas, ou Ruido<br/>
> <img height="200px" src="http://victorvenites.com/recursos_diversos/Deterministico_Stocastico_Noise.png" align="center" hspace="20px" vspace="5px"><br/>
---

# Rede Simples / Perceptron
> Rede Neural de 1 Camadas

In [3]:
# Dependencias
import numpy as np
# Para matemática, pois Python não foi criado para calculadora, multiplicação de matriz
import time # Para registrar o tempo de uma execução

In [4]:
# Variáveis
n_hidden = 10 # 10 neurônios por camada interna
n_in = 10 # Dados/Neurônios de Entrada

# Saidas
n_out = 10 # Neuronios de Saída
n_sample = 300 # Dados

# HyperParametro - Graus de Entropía?
learning_rate = 0.10 # Qual a velocidade
momentum = 0.9 # 

# Semente Aleatória - Não Deterministica
np.random.seed(0)

In [5]:
# Trecho para normalização dos resultados de cada treino

# Para Camada Única
def sigmoid(x): #Popularmente usada por ter curvas abrangentes
  return 1.0/(1.0 + np.exp(-x)) # Torna os número em probabílidades

## Diagrama de Camadas
> <img height="500px" src="http://victorvenites.com/recursos_diversos/Diagrama_Camadas.png" align="center" hspace="20px" vspace="5px"><br/>

In [12]:
# Entrada de Dados, Transpose, Camada 1, Biases
def train(x, t, W, bw): #x = input; t = Transposta; W = Camadas; bw = Viés
    #forward -- matrix multiply + Biases
    # Primeira Camada
    A = np.dot(x, W) + bw # Multiplica os dados de entrada pela primeira camada
    Y = sigmoid(A) # Função de ativação

    #backward - Para minimizar a perda
    Ew = Y - t
    

    #predizer a perda
    dW = np.outer(x, Ew) # Delta camada

    # Mutilplicação da Transposta Inversa
    loss = -np.mean(t * np.log(Y) + (1 - t) * np.log(1 - Y))
    # Signal --> Sinal do Neuronio segundo autor

    return loss, (dW, Ew)

In [6]:
def predict(x, W,  bw):
    A = np.dot(x, W) + bw # Valores finais da predição

    return (sigmoid(A) > 0.5).astype(int) # se maior que 0.5, vira 1/ Se menor vira zero

In [7]:
# Criação das Camadas
W = np.random.normal(scale=0.1, size=(n_in, n_hidden)) # Primeira camada, Matriz de zeros
# W = np.random.normal(scale=0.1, size=(n_hidden, n_out)) # Segunda camada, Matriz de zeros
# 10 entram, 10 saem

bw = np.zeros(n_hidden) # 
# bw = np.zeros(n_out)

params = [W, bw]
params

[array([[ 0.17640523,  0.04001572,  0.0978738 ,  0.22408932,  0.1867558 ,
         -0.09772779,  0.09500884, -0.01513572, -0.01032189,  0.04105985],
        [ 0.01440436,  0.14542735,  0.07610377,  0.0121675 ,  0.04438632,
          0.03336743,  0.14940791, -0.02051583,  0.03130677, -0.08540957],
        [-0.25529898,  0.06536186,  0.08644362, -0.0742165 ,  0.22697546,
         -0.14543657,  0.00457585, -0.01871839,  0.15327792,  0.14693588],
        [ 0.01549474,  0.03781625, -0.08877857, -0.19807965, -0.03479121,
          0.0156349 ,  0.12302907,  0.12023798, -0.03873268, -0.03023028],
        [-0.1048553 , -0.14200179, -0.17062702,  0.19507754, -0.05096522,
         -0.04380743, -0.12527954,  0.07774904, -0.16138978, -0.02127403],
        [-0.08954666,  0.03869025, -0.05108051, -0.11806322, -0.00281822,
          0.04283319,  0.00665172,  0.03024719, -0.06343221, -0.03627412],
        [-0.06724604, -0.03595532, -0.08131463, -0.17262826,  0.01774261,
         -0.04017809, -0.1630198

In [10]:
#Gerar os Dados - Teste com portas lógicas
X = np.random.binomial(1, 0.5, (n_sample, n_in))
T  = X ^ 1 # XOR, OU Exclusivo
# O síbomlo '^' é um comando lógico do python entre 'a' e 'b'
# Ex: 0 ^ 1 -> 1; 1 ^ 1 -> 0 ; 
X, T

(array([[1, 1, 0, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 1, 0],
        [0, 1, 1, ..., 0, 0, 1],
        ...,
        [0, 1, 0, ..., 0, 0, 1],
        [1, 1, 0, ..., 0, 1, 0],
        [0, 0, 1, ..., 0, 0, 1]]), array([[0, 0, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 0, 1],
        [1, 0, 0, ..., 1, 1, 0],
        ...,
        [1, 0, 1, ..., 1, 1, 0],
        [0, 0, 1, ..., 1, 0, 1],
        [1, 1, 0, ..., 1, 1, 0]], dtype=int32))

In [13]:
# Hora do modelo
for epoch in range(100): # Época do treinamento
  err = []
  upd = [0]*len(params) # Update
  
  t0 = time.clock()
  # para cada ponto do dado, atualize nossos pesos
  for i in range(X.shape[0]):
    loss, grad = train(X[i], T[i], *params)
    # Como posso garantir que esta certo?
    #Atualizar a perda
    for j in range(len(params)):
      params[j] -= upd[j]
    
    for k in range(len(params)):
        upd[k] = learning_rate * grad[k] + momentum * upd[k]
        # DataFitting
      
    err.append(loss)
  
  print('Epoch: %d, Loos: %.8f, Time: %fs' %(epoch, np.mean(err), time.clock()-t0))

E:\Users\Palmito\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
E:\Users\Palmito\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


Epoch: 0, Loos: 0.11496093, Time: 0.015671s
Epoch: 1, Loos: 0.00838854, Time: 0.011688s
Epoch: 2, Loos: 0.00544919, Time: 0.014808s
Epoch: 3, Loos: 0.00408101, Time: 0.014017s
Epoch: 4, Loos: 0.00327394, Time: 0.016711s
Epoch: 5, Loos: 0.00273796, Time: 0.026012s
Epoch: 6, Loos: 0.00235493, Time: 0.013668s
Epoch: 7, Loos: 0.00206707, Time: 0.011261s
Epoch: 8, Loos: 0.00184259, Time: 0.012582s
Epoch: 9, Loos: 0.00166251, Time: 0.011580s
Epoch: 10, Loos: 0.00151477, Time: 0.011299s
Epoch: 11, Loos: 0.00139133, Time: 0.011203s
Epoch: 12, Loos: 0.00128663, Time: 0.015063s
Epoch: 13, Loos: 0.00119669, Time: 0.016670s
Epoch: 14, Loos: 0.00111857, Time: 0.019437s
Epoch: 15, Loos: 0.00105007, Time: 0.030849s
Epoch: 16, Loos: 0.00098953, Time: 0.016791s
Epoch: 17, Loos: 0.00093562, Time: 0.023765s
Epoch: 18, Loos: 0.00088731, Time: 0.011399s
Epoch: 19, Loos: 0.00084376, Time: 0.018659s
Epoch: 20, Loos: 0.00080431, Time: 0.012049s
Epoch: 21, Loos: 0.00076839, Time: 0.011534s
Epoch: 22, Loos: 0.0

# Vamos tentar predizer algo

In [14]:
#Vamos tentar predizer algo
x = np.random.binomial(1, 0.5, n_in)
print('Predição XOR')
print(x)
print(predict(x, *params))

Predição XOR
[0 1 1 1 0 0 1 0 0 0]
[1 0 0 0 1 1 0 1 1 1]


In [16]:
1 ^ 1

0